# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool2/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool2/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1F12-74BD";
      fsType = "vfat";
    };

  fileSystems."/var/lib/syncthing" =
    { device = "rpool2/syncthing";
      fsType = "zfs";
    };

  fileSystems."/var/lib/syncthing/Personal" =
    { device = "rpool2/syncthing/Personal";
      fsType = "zfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/8291e3aa-369e-4610-9c01-dde51c27087f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ifb0.useDHCP = lib.mkDefault true;
  # networking.interfaces.ifb1.useDHCP = lib.mkDefault true;
  # networking.interfaces.lan.useDHCP = lib.mkDefault true;
  # networking.interfaces.vl_guest.useDHCP = lib.mkDefault true;
  # networking.interfaces.vl_IoT.useDHCP = lib.mkDefault true;
  # networking.interfaces.vl_local.useDHCP = lib.mkDefault true;
  # networking.interfaces.vl_mgmt.useDHCP = lib.mkDefault true;
  # networking.interfaces.vl_trusted.useDHCP = lib.mkDefault true;
  # networking.interfaces.wan.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
